-- ============================================================
--  TrovaImpresa — Vetrina prodotti dei NEGOZI
--  Tabella + RLS. Sicuro da rieseguire (idempotente).
--  La foto usa il bucket storage "foto-lavori" (già esistente e pubblico).
--  Limite piano Free (max 3 prodotti) gestito lato app in pannello-negozio.html.
-- ============================================================

create table if not exists public.vetrina_negozio (
  id          bigint generated by default as identity primary key,
  negozio_id  uuid not null references auth.users(id) on delete cascade,
  titolo      text not null,
  categoria   text,
  prezzo      numeric,
  dettagli    text,
  foto        text,
  in_vetrina  boolean not null default true,
  created_at  timestamptz not null default now()
);

create index if not exists idx_vetrina_negozio_id on public.vetrina_negozio (negozio_id);

alter table public.vetrina_negozio enable row level security;

-- Lettura pubblica: serve al profilo pubblico del negozio (profilo-impresa.html)
drop policy if exists vetrina_select_public on public.vetrina_negozio;
create policy vetrina_select_public
  on public.vetrina_negozio for select
  using (true);

-- Ogni negozio gestisce SOLO i propri prodotti
drop policy if exists vetrina_insert_own on public.vetrina_negozio;
create policy vetrina_insert_own
  on public.vetrina_negozio for insert
  with check (auth.uid() = negozio_id);

drop policy if exists vetrina_update_own on public.vetrina_negozio;
create policy vetrina_update_own
  on public.vetrina_negozio for update
  using (auth.uid() = negozio_id);

drop policy if exists vetrina_delete_own on public.vetrina_negozio;
create policy vetrina_delete_own
  on public.vetrina_negozio for delete
  using (auth.uid() = negozio_id);
